name: wild_scan_ai
description: "WildScanAI uses AI to instantly identify insects, reptiles, and arachnids—your smart companion for nature adventures."

publish_to: 'none'

version: 1.0.0+3

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.1.0
  avatar_glow: ^2.0.1
  image_picker: ^1.1.2
  intl: ^0.20.2
  image: any
  dotted_border: ^2.1.0
  flutter_chat_types: ^3.6.2
  flutter_chat_ui: ^1.6.15
  uuid: ^4.5.1
  collection: ^1.19.1
  font_awesome_flutter: ^10.8.0
  flutter_markdown: ^0.6.18

  shimmer: ^3.0.0
  percent_indicator: ^4.2.3
  confetti: ^0.8.0
  badges: ^3.1.2
  google_fonts: ^6.2.1
  flutter_typeahead: ^5.2.0

  flash_card: ^0.1.0
  flutter_chat_bubble: ^2.0.2
  flutter_spinkit: ^5.2.1
  camera: ^0.11.1
  permission_handler: ^12.0.0+1
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  provider: ^6.1.1
  path: ^1.8.3
  syncfusion_flutter_charts: ^29.1.40
  water_drop_nav_bar: ^2.2.2
  syncfusion_flutter_gauges: ^29.1.40
  mobile_scanner: ^7.0.0
  shared_preferences: ^2.5.3
  google_mobile_ads: ^4.0.0
  share_plus: ^7.2.1

  # Gemini AI için
  google_generative_ai: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - images/