import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'dart:math';

class LanguageService extends ChangeNotifier {
  static const String _languageKey = 'selected_language';
  Locale? _currentLocale;
  Locale? get currentLocale => _currentLocale;
  String get currentLanguage => _currentLocale?.languageCode ?? 'en';

  // Desteklenen diller
  static const Map<String, Map<String, String>> supportedLanguages = {
    'en': {
      'name': 'English',
      'nativeName': 'English',
      'flag': '🇺🇸',
    },
    'es': {
      'name': 'Spanish',
      'nativeName': 'Español',
      'flag': '🇪🇸',
    },
    'hi': {
      'name': 'Hindi',
      'nativeName': 'हिन्दी',
      'flag': '🇮🇳',
    },
    'ar': {
      'name': 'Arabic',
      'nativeName': 'العربية',
      'flag': '🇸🇦',
    },
    'id': {
      'name': 'Indonesian',
      'nativeName': 'Bahasa Indonesia',
      'flag': '🇮🇩',
    },
    'vi': {
      'name': 'Vietnamese',
      'nativeName': 'Tiếng Việt',
      'flag': '🇻🇳',
    },
    'ko': {
      'name': 'Korean',
      'nativeName': '한국어',
      'flag': '🇰🇷',
    },
    'ja': {
      'name': 'Japanese',
      'nativeName': '日本語',
      'flag': '🇯🇵',
    },
    'tr': {
      'name': 'Turkish',
      'nativeName': 'Türkçe',
      'flag': '🇹🇷',
    },
  };

  // Çeviriler - Böcek ve Sürüngen Temalı
  static const Map<String, Map<String, String>> translations = {
    'en': {
      'select_language': 'Select Language',
      'choose_your_language': 'Choose your preferred language',
      'continue': 'Continue',
      'bug_scanner': 'Bug Scanner',
      'discover_world_of_insects': 'Discover the World of Insects & Reptiles',
      'ai_powered': 'AI Powered',
      'instant_results': 'Instant Results',
      'initializing': 'Initializing...',
      'scan_bug': 'Scan Bug',
      'ai_chat': 'AI Chat',
      'collection': 'Collection',
      'progress': 'Progress',
      'history': 'History',
      'home': 'Home',
      'search_bugs': 'Search for insects...',
      'identify_bugs': 'Identify Insects',
      'take_photo': 'Take Photo',
      'gallery': 'Gallery',
      'capture_photo': 'Capture a photo of the insect',
      'choose_gallery': 'Choose from your gallery',
      'recent_identifications': 'Recent Identifications',
      'view_all': 'View All',
      'no_bugs_yet': 'No insects identified yet',
      'no_bugs_identified': 'No bugs identified yet',
      'start_photo': 'Start by taking a photo of an insect',
      'ai_bug_expert': 'AI Bug Expert',
      'entomology_assistant': 'Entomology Assistant',
      'ask_anything': 'Ask me anything about insects and reptiles!',
      'hello_message': 'Hello! I\'m your entomology assistant. How can I help you today?',
      'type_message': 'Type your message...',
      'venomous_tip': 'Many insects and reptiles can be venomous. Always maintain a safe distance and avoid handling unknown species.',
      'identification_tip': 'Look for key features like body shape, color patterns, number of legs, and antennae for accurate identification.',
      'habitat_tip': 'Different insects prefer different environments. Knowing the habitat can help with identification.',
      'danger_tip': 'Some insects and reptiles can be dangerous. Always prioritize safety and avoid direct contact.',
      'disease_tip': 'Certain insects can carry diseases. Be aware of potential health risks in your area.',
      'safety_tip': 'When encountering unknown insects or reptiles, observe from a distance and avoid provoking them.',
      'general_help': 'I can help with insect identification, venom assessment, habitat information, and safety tips. What specific topic would you like to know more about?',
      'bug_fact_of_day': 'Bug Fact of the Day',
      'bug_fact_content': 'There are over 1 million known species of insects, making them the most diverse group of animals on Earth!',
      'danger_level': 'Danger Level',
      'description': 'Description',
      'venomous': 'Venomous',
      'species': 'Species',
      'habitat': 'Habitat',
      'diseases': 'Diseases',
      'safety_tips': 'Safety Tips',
      'high_danger': 'High Danger',
      'medium_danger': 'Medium Danger',
      'low_danger': 'Low Danger',
      'yes': 'Yes',
      'no': 'No',
      'unknown': 'Unknown',
      'analyzing': 'Analyzing...',
      'analysis_complete': 'Analysis Complete',
      'error_occurred': 'An error occurred',
      'try_again': 'Try Again',
      'share_result': 'Share Result',
      'save_to_gallery': 'Save to Gallery',
      'delete_record': 'Delete Record',
      'confirm_delete': 'Are you sure you want to delete this record?',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'no_records_found': 'No records found',
      'scan_new_bug': 'Scan New Bug',
      'dangerous_species': 'Dangerous Species',
      'safe_species': 'Safe Species',
      'venomous_species': 'Venomous Species',
      'non_venomous': 'Non-venomous',
      'common_habitats': 'Common Habitats',
      'prevention_tips': 'Prevention Tips',
      'emergency_contact': 'Emergency Contact',
      'medical_attention': 'Seek medical attention if bitten',
      'keep_distance': 'Keep a safe distance',
      'do_not_touch': 'Do not touch or handle',
      'call_expert': 'Call a local expert',
      'insect_identification': 'Insect Identification',
      'reptile_identification': 'Reptile Identification',
      'spider_identification': 'Spider Identification',
      'snake_identification': 'Snake Identification',
      'scorpion_identification': 'Scorpion Identification',
      'beetle_identification': 'Beetle Identification',
      'butterfly_identification': 'Butterfly Identification',
      'ant_identification': 'Ant Identification',
      'bee_identification': 'Bee Identification',
      'wasp_identification': 'Wasp Identification',
      'mosquito_identification': 'Mosquito Identification',
      'tick_identification': 'Tick Identification',
      'centipede_identification': 'Centipede Identification',
      'millipede_identification': 'Millipede Identification',
      'cricket_identification': 'Cricket Identification',
      'grasshopper_identification': 'Grasshopper Identification',
      'ladybug_identification': 'Ladybug Identification',
      'dragonfly_identification': 'Dragonfly Identification',
      'firefly_identification': 'Firefly Identification',
      'moth_identification': 'Moth Identification',
      'fly_identification': 'Fly Identification',
      'flea_identification': 'Flea Identification',
      'louse_identification': 'Louse Identification',
      'bedbug_identification': 'Bedbug Identification',
      'termite_identification': 'Termite Identification',
      'cockroach_identification': 'Cockroach Identification',
      'earwig_identification': 'Earwig Identification',
      'silverfish_identification': 'Silverfish Identification',
      'booklice_identification': 'Booklice Identification',
      'springtail_identification': 'Springtail Identification',
      'thrips_identification': 'Thrips Identification',
      'aphid_identification': 'Aphid Identification',
      'scale_insect_identification': 'Scale Insect Identification',
      'mealybug_identification': 'Mealybug Identification',
      'whitefly_identification': 'Whitefly Identification',
      'leafhopper_identification': 'Leafhopper Identification',
      'planthopper_identification': 'Planthopper Identification',
      'treehopper_identification': 'Treehopper Identification',
      'cicada_identification': 'Cicada Identification',
      'spittlebug_identification': 'Spittlebug Identification',
      'froghopper_identification': 'Froghopper Identification',
      'psyllid_identification': 'Psyllid Identification',
      'bug_identifier': 'Bug Identifier',
      'discover_world_of_bugs': 'Discover the World of Bugs',
      'bug_fact_1': 'There are more than 1 million known species of insects on Earth.',
      'bug_fact_2': 'Ants can lift objects 50 times their own body weight.',
      'bug_fact_3': 'Dragonflies can fly up to 60 km/h, making them one of the fastest insects.',
      'bug_fact_4': 'Bees communicate with each other by dancing.',
      'bug_fact_5': 'Butterflies taste with their feet.',
      'bug_fact_6': 'Some beetles can glow in the dark, like fireflies.',
      'bug_fact_7': 'Mosquitoes are attracted to people who have just eaten bananas.',
      'bug_fact_8': 'A cockroach can live for a week without its head.',
      'bug_fact_9': 'Ladybugs can eat up to 5,000 aphids in their lifetime.',
      'bug_fact_10': 'Termites never sleep and can work 24 hours a day.',
      'bug_fact_11': 'The world\'s largest insect is the Goliath beetle.',
      'bug_fact_12': 'Some butterflies migrate thousands of kilometers each year.',
      'bug_fact_13': 'Praying mantises can turn their heads 180 degrees.',
      'bug_fact_14': 'Fleas can jump 200 times their body length.',
      'bug_fact_15': 'Stick insects can blend perfectly with twigs and leaves.',
      'bug_fact_16': 'Honey never spoils thanks to enzymes from bees.',
      'bug_fact_17': 'Some ants farm fungi for food.',
      'bug_fact_18': 'Cicadas can live underground for up to 17 years.',
      'bug_fact_19': 'Fire ants can form living rafts to survive floods.',
      'bug_fact_20': 'The bombardier beetle defends itself by shooting hot chemicals.',
    },
    'tr': {
      'select_language': 'Dil Seçin',
      'choose_your_language': 'Tercih ettiğiniz dili seçin',
      'continue': 'Devam Et',
      'bug_scanner': 'Böcek Tarayıcı',
      'discover_world_of_insects': 'Böcekler ve Sürüngenler Dünyasını Keşfedin',
      'ai_powered': 'AI Destekli',
      'instant_results': 'Anında Sonuçlar',
      'initializing': 'Başlatılıyor...',
      'scan_bug': 'Böcek Tara',
      'ai_chat': 'AI Sohbet',
      'collection': 'Koleksiyon',
      'progress': 'İlerleme',
      'history': 'Geçmiş',
      'home': 'Ana Sayfa',
      'search_bugs': 'Böcek ara...',
      'identify_bugs': 'Böcekleri Tanımla',
      'take_photo': 'Fotoğraf Çek',
      'gallery': 'Galeri',
      'capture_photo': 'Böceğin fotoğrafını çekin',
      'choose_gallery': 'Galerinizden seçin',
      'recent_identifications': 'Son Tanımlamalar',
      'view_all': 'Tümünü Gör',
      'no_bugs_yet': 'Henüz böcek tanımlanmadı',
      'no_bugs_identified': 'Henüz böcek tanımlanmadı',
      'start_photo': 'Bir böceğin fotoğrafını çekerek başlayın',
      'ai_bug_expert': 'AI Böcek Uzmanı',
      'entomology_assistant': 'Entomoloji Asistanı',
      'ask_anything': 'Böcekler ve sürüngenler hakkında herhangi bir şey sorabilirsiniz!',
      'hello_message': 'Merhaba! Ben entomoloji asistanınızım. Bugün size nasıl yardımcı olabilirim?',
      'type_message': 'Mesajınızı yazın...',
      'venomous_tip': 'Birçok böcek ve sürüngen zehirli olabilir. Her zaman güvenli mesafeyi koruyun ve bilinmeyen türleri ellemekten kaçının.',
      'identification_tip': 'Doğru tanımlama için vücut şekli, renk desenleri, bacak sayısı ve antenler gibi temel özelliklere bakın.',
      'habitat_tip': 'Farklı böcekler farklı ortamları tercih eder. Habitatı bilmek tanımlamaya yardımcı olabilir.',
      'danger_tip': 'Bazı böcekler ve sürüngenler tehlikeli olabilir. Her zaman güvenliği öncelik edin ve doğrudan temastan kaçının.',
      'disease_tip': 'Bazı böcekler hastalık taşıyabilir. Bölgenizdeki potansiyel sağlık risklerinin farkında olun.',
      'safety_tip': 'Bilinmeyen böcekler veya sürüngenlerle karşılaştığınızda, mesafeden gözlemleyin ve onları provoke etmekten kaçının.',
      'general_help': 'Böcek tanımlama, zehir değerlendirmesi, habitat bilgisi ve güvenlik ipuçları konularında yardımcı olabilirim. Hangi konu hakkında daha fazla bilgi almak istiyorsunuz?',
      'bug_fact_of_day': 'Günün Böcek Gerçeği',
      'bug_fact_content': 'Dünyada 1 milyondan fazla bilinen böcek türü var, bu da onları dünyadaki en çeşitli hayvan grubu yapıyor!',
      'danger_level': 'Tehlike Seviyesi',
      'description': 'Açıklama',
      'venomous': 'Zehirli',
      'species': 'Tür',
      'habitat': 'Habitat',
      'diseases': 'Hastalıklar',
      'safety_tips': 'Güvenlik İpuçları',
      'high_danger': 'Yüksek Tehlike',
      'medium_danger': 'Orta Tehlike',
      'low_danger': 'Düşük Tehlike',
      'yes': 'Evet',
      'no': 'Hayır',
      'unknown': 'Bilinmiyor',
      'analyzing': 'Analiz ediliyor...',
      'analysis_complete': 'Analiz Tamamlandı',
      'error_occurred': 'Bir hata oluştu',
      'try_again': 'Tekrar Dene',
      'share_result': 'Sonucu Paylaş',
      'save_to_gallery': 'Galeriye Kaydet',
      'delete_record': 'Kaydı Sil',
      'confirm_delete': 'Bu kaydı silmek istediğinizden emin misiniz?',
      'cancel': 'İptal',
      'delete': 'Sil',
      'no_records_found': 'Kayıt bulunamadı',
      'scan_new_bug': 'Yeni Böcek Tara',
      'dangerous_species': 'Tehlikeli Türler',
      'safe_species': 'Güvenli Türler',
      'venomous_species': 'Zehirli Türler',
      'non_venomous': 'Zehirsiz',
      'common_habitats': 'Yaygın Habitatlar',
      'prevention_tips': 'Önleme İpuçları',
      'emergency_contact': 'Acil Durum İletişimi',
      'medical_attention': 'Isırılırsanız tıbbi yardım alın',
      'keep_distance': 'Güvenli mesafeyi koruyun',
      'do_not_touch': 'Dokunmayın veya ellemeyin',
      'call_expert': 'Yerel bir uzmanı arayın',
      'insect_identification': 'Böcek Tanımlama',
      'reptile_identification': 'Sürüngen Tanımlama',
      'spider_identification': 'Örümcek Tanımlama',
      'snake_identification': 'Yılan Tanımlama',
      'scorpion_identification': 'Akrep Tanımlama',
      'beetle_identification': 'Böcek Tanımlama',
      'butterfly_identification': 'Kelebek Tanımlama',
      'ant_identification': 'Karınca Tanımlama',
      'bee_identification': 'Arı Tanımlama',
      'wasp_identification': 'Eşek Arısı Tanımlama',
      'mosquito_identification': 'Sivrisinek Tanımlama',
      'tick_identification': 'Kene Tanımlama',
      'centipede_identification': 'Kırkayak Tanımlama',
      'millipede_identification': 'Çokayak Tanımlama',
      'cricket_identification': 'Cırcır Böceği Tanımlama',
      'grasshopper_identification': 'Çekirge Tanımlama',
      'ladybug_identification': 'Uğur Böceği Tanımlama',
      'dragonfly_identification': 'Yusufçuk Tanımlama',
      'firefly_identification': 'Ateş Böceği Tanımlama',
      'moth_identification': 'Güve Tanımlama',
      'fly_identification': 'Sinek Tanımlama',
      'flea_identification': 'Pire Tanımlama',
      'louse_identification': 'Louse Identification',
      'bedbug_identification': 'Bedbug Identification',
      'termite_identification': 'Termite Identification',
      'cockroach_identification': 'Cockroach Identification',
      'earwig_identification': 'Earwig Identification',
      'silverfish_identification': 'Silverfish Identification',
      'booklice_identification': 'Booklice Identification',
      'springtail_identification': 'Springtail Identification',
      'thrips_identification': 'Thrips Identification',
      'aphid_identification': 'Aphid Identification',
      'scale_insect_identification': 'Scale Insect Identification',
      'mealybug_identification': 'Mealybug Identification',
      'whitefly_identification': 'Whitefly Identification',
      'leafhopper_identification': 'Leafhopper Identification',
      'planthopper_identification': 'Planthopper Identification',
      'treehopper_identification': 'Treehopper Identification',
      'cicada_identification': 'Cicada Identification',
      'spittlebug_identification': 'Spittlebug Identification',
      'froghopper_identification': 'Froghopper Identification',
      'psyllid_identification': 'Psyllid Identification',
      'bug_identifier': 'Böcek Tanımlayıcı',
      'discover_world_of_bugs': 'Böcekler Dünyasını Keşfet',
      'bug_fact_1': 'Dünyada 1 milyondan fazla bilinen böcek türü vardır.',
      'bug_fact_2': 'Karıncalar kendi ağırlıklarının 50 katını kaldırabilir.',
      'bug_fact_3': 'Yusufçuklar saatte 60 km hıza ulaşabilir, en hızlı böceklerdendir.',
      'bug_fact_4': 'Arılar birbirleriyle dans ederek iletişim kurar.',
      'bug_fact_5': 'Kelebekler tat alma duyusunu ayaklarında taşır.',
      'bug_fact_6': 'Bazı böcekler, ateş böcekleri gibi karanlıkta parlayabilir.',
      'bug_fact_7': 'Sivrisinekler muz yiyen insanlara daha çok yaklaşır.',
      'bug_fact_8': 'Bir hamam böceği başı olmadan bir hafta yaşayabilir.',
      'bug_fact_9': 'Uğur böcekleri ömürleri boyunca 5.000 yaprak biti yiyebilir.',
      'bug_fact_10': 'Termitler hiç uyumaz ve günde 24 saat çalışabilir.',
      'bug_fact_11': 'Dünyanın en büyük böceği Goliath böceğidir.',
      'bug_fact_12': 'Bazı kelebekler her yıl binlerce kilometre göç eder.',
      'bug_fact_13': 'Peygamberdeveleri başlarını 180 derece çevirebilir.',
      'bug_fact_14': 'Pireler vücutlarının 200 katı kadar zıplayabilir.',
      'bug_fact_15': 'Çubuk böcekleri dallar ve yapraklarla mükemmel kamufle olur.',
      'bug_fact_16': 'Bal, arıların enzimleri sayesinde asla bozulmaz.',
      'bug_fact_17': 'Bazı karıncalar yiyecek için mantar yetiştirir.',
      'bug_fact_18': 'Ağustos böcekleri yer altında 17 yıla kadar yaşayabilir.',
      'bug_fact_19': 'Ateş karıncaları selde hayatta kalmak için canlı sal oluşturabilir.',
      'bug_fact_20': 'Bombardıman böceği kendini sıcak kimyasal püskürterek korur.',
    },
    'es': {
      'select_language': 'Seleccionar Idioma',
      'choose_your_language': 'Elige tu idioma preferido',
      'continue': 'Continuar',
      'bug_scanner': 'Escáner de Bichos',
      'discover_world_of_insects': 'Descubre el Mundo de Insectos y Reptiles',
      'ai_powered': 'AI Potenciado',
      'instant_results': 'Resultados Instantáneos',
      'initializing': 'Inicializando...',
      'scan_bug': 'Escanear Bicho',
      'ai_chat': 'Chat AI',
      'collection': 'Colección',
      'progress': 'Progreso',
      'history': 'Historial',
      'home': 'Inicio',
      'search_bugs': 'Buscar insectos...',
      'identify_bugs': 'Identificar Insectos',
      'take_photo': 'Tomar Foto',
      'gallery': 'Galería',
      'capture_photo': 'Captura una foto del insecto',
      'choose_gallery': 'Elige de tu galería',
      'recent_identifications': 'Identificaciones Recientes',
      'view_all': 'Ver Todo',
      'no_bugs_yet': 'Aún no se han identificado insectos',
      'no_bugs_identified': 'Aún no se han identificado bichos',
      'start_photo': 'Comienza tomando una foto de un insecto',
      'ai_bug_expert': 'Experto de Bichos AI',
      'entomology_assistant': 'Asistente de Entomología',
      'ask_anything': '¡Pregúntame cualquier cosa sobre insectos y reptiles!',
      'hello_message': '¡Hola! Soy tu asistente de entomología. ¿Cómo te puedo ayudar hoy?',
      'type_message': 'Escribe tu mensaje...',
      'venomous_tip': 'Muchos insectos y reptiles pueden ser venenosos. Mantén siempre una distancia segura y evita tocar especies desconocidas.',
      'identification_tip': 'Busca características clave como forma del cuerpo, patrones de color, número de patas y antenas para una identificación precisa.',
      'habitat_tip': 'Los insectos prefieren diferentes hábitats. Conocer el hábitat puede ayudar con la identificación.',
      'danger_tip': 'Algunos insectos y reptiles pueden ser peligrosos. Siempre prioriza la seguridad y evita el contacto directo.',
      'disease_tip': 'Algunos insectos pueden transmitir enfermedades. Mantén alerta sobre los riesgos de salud en tu área.',
      'safety_tip': 'Cuando encuentres insectos o reptiles desconocidos, observa desde una distancia y evita provocarlos.',
      'general_help': 'Puedo ayudarte con la identificación de insectos, evaluación de veneno, información de hábitat y consejos de seguridad. ¿Qué tema te gustaría saber más?',
      'bug_fact_of_day': 'Hecho del Día de los Bichos',
      'bug_fact_content': 'Hay más de 1 millón de especies conocidas de insectos, lo que los hace el grupo de animales más diverso en la Tierra!',
      'danger_level': 'Nivel de Peligro',
      'description': 'Descripción',
      'venomous': 'Venenoso',
      'species': 'Especie',
      'habitat': 'Hábitat',
      'diseases': 'Enfermedades',
      'safety_tips': 'Consejos de Seguridad',
      'high_danger': 'Peligro Alto',
      'medium_danger': 'Peligro Medio',
      'low_danger': 'Peligro Bajo',
      'yes': 'Sí',
      'no': 'No',
      'unknown': 'Desconocido',
      'analyzing': 'Analizando...',
      'analysis_complete': 'Análisis Completo',
      'error_occurred': 'Ocurrió un error',
      'try_again': 'Inténtalo de nuevo',
      'share_result': 'Compartir Resultado',
      'save_to_gallery': 'Guardar en Galería',
      'delete_record': 'Eliminar Registro',
      'confirm_delete': '¿Estás seguro de que quieres eliminar este registro?',
      'cancel': 'Cancelar',
      'delete': 'Eliminar',
      'no_records_found': 'No se encontraron registros',
      'scan_new_bug': 'Escanear Nuevo Bicho',
      'dangerous_species': 'Especies Peligrosas',
      'safe_species': 'Especies Seguras',
      'venomous_species': 'Especies Venenosas',
      'non_venomous': 'No Venenoso',
      'common_habitats': 'Hábitats Comunes',
      'prevention_tips': 'Consejos de Prevención',
      'emergency_contact': 'Contacto de Emergencia',
      'medical_attention': 'Busca atención médica si te muerden',
      'keep_distance': 'Mantén una distancia segura',
      'do_not_touch': 'No lo toques ni manejes',
      'call_expert': 'Llama a un experto local',
      'insect_identification': 'Identificación de Insectos',
      'reptile_identification': 'Identificación de Reptiles',
      'spider_identification': 'Identificación de Arañas',
      'snake_identification': 'Identificación de Serpientes',
      'scorpion_identification': 'Identificación de Escorpiones',
      'beetle_identification': 'Identificación de Escarabajos',
      'butterfly_identification': 'Identificación de Mariposas',
      'ant_identification': 'Identificación de Hormigas',
      'bee_identification': 'Identificación de Abejas',
      'wasp_identification': 'Identificación de Avispas',
      'mosquito_identification': 'Identificación de Mosquitos',
      'tick_identification': 'Identificación de Pulgas',
      'centipede_identification': 'Identificación de Centópodo',
      'millipede_identification': 'Identificación de Milípodo',
      'cricket_identification': 'Identificación de Cíclido',
      'grasshopper_identification': 'Identificación de Saltamontes',
      'ladybug_identification': 'Identificación de Mariposa de la Mano',
      'dragonfly_identification': 'Identificación de Grulla',
      'firefly_identification': 'Identificación de Luciérnaga',
      'moth_identification': 'Identificación de Hormiga',
      'fly_identification': 'Identificación de Mosca',
      'flea_identification': 'Identificación de Piojos',
      'louse_identification': 'Identificación de Piojos',
      'bedbug_identification': 'Identificación de Pulgas de Cama',
      'termite_identification': 'Identificación de Hormiga de Madera',
      'cockroach_identification': 'Identificación de Hormiga de Casa',
      'earwig_identification': 'Identificación de Escarabajo de Oído',
      'silverfish_identification': 'Identificación de Pulga de Goma',
      'booklice_identification': 'Identificación de Pulga de Libro',
      'springtail_identification': 'Identificación de Gusano de Primavera',
      'thrips_identification': 'Identificación de Trips',
      'aphid_identification': 'Identificación de Pulga de Hoja',
      'scale_insect_identification': 'Identificación de Pulga de Escala',
      'mealybug_identification': 'Identificación de Pulga de Miel',
      'whitefly_identification': 'Identificación de Pulga Blanca',
      'leafhopper_identification': 'Identificación de Pulga de Hoja',
      'planthopper_identification': 'Identificación de Pulga de Planta',
      'treehopper_identification': 'Identificación de Pulga de Árbol',
      'cicada_identification': 'Identificación de Cicada',
      'spittlebug_identification': 'Identificación de Pulga de Túnel',
      'froghopper_identification': 'Identificación de Pulga de Rana',
      'psyllid_identification': 'Identificación de Pulga de Psilófito',
      'bug_identifier': 'Identificador de insectos',
      'discover_world_of_bugs': 'Descubre el mundo de los insectos',
      'bug_fact_1': 'Hay más de 1 millón de especies conocidas de insectos en la Tierra.',
      'bug_fact_2': 'Las hormigas pueden levantar objetos 50 veces su propio peso.',
      'bug_fact_3': 'Las libélulas pueden volar hasta 60 km/h, siendo de los insectos más rápidos.',
      'bug_fact_4': 'Las abejas se comunican bailando.',
      'bug_fact_5': 'Las mariposas saborean con sus pies.',
      'bug_fact_6': 'Algunos escarabajos pueden brillar en la oscuridad, como las luciérnagas.',
      'bug_fact_7': 'Los mosquitos se sienten atraídos por personas que han comido plátanos.',
      'bug_fact_8': 'Una cucaracha puede vivir una semana sin cabeza.',
      'bug_fact_9': 'Las mariquitas pueden comer hasta 5,000 pulgones en su vida.',
      'bug_fact_10': 'Las termitas nunca duermen y pueden trabajar 24 horas al día.',
      'bug_fact_11': 'El insecto más grande del mundo es el escarabajo Goliat.',
      'bug_fact_12': 'Algunas mariposas migran miles de kilómetros cada año.',
      'bug_fact_13': 'Las mantis religiosas pueden girar la cabeza 180 grados.',
      'bug_fact_14': 'Las pulgas pueden saltar 200 veces su longitud corporal.',
      'bug_fact_15': 'Los insectos palo se camuflan perfectamente con ramas y hojas.',
      'bug_fact_16': 'La miel nunca se estropea gracias a las enzimas de las abejas.',
      'bug_fact_17': 'Algunas hormigas cultivan hongos para alimentarse.',
      'bug_fact_18': 'Las cigarras pueden vivir bajo tierra hasta 17 años.',
      'bug_fact_19': 'Las hormigas de fuego pueden formar balsas vivas para sobrevivir a inundaciones.',
      'bug_fact_20': 'El escarabajo bombardero se defiende disparando químicos calientes.',
    },
    'hi': {
      'select_language': 'भाषा चुनें',
      'choose_your_language': 'अपनी पसंदीदा भाषा चुनें',
      'continue': 'जारी रखें',
      'bug_scanner': 'बग स्कैनर',
      'discover_world_of_insects': 'बग और पक्षी दुनिया की खोज करें',
      'ai_powered': 'AI शक्तिशाली',
      'instant_results': 'तुरंत परिणाम',
      'initializing': 'शुरू हो रहा है...',
      'scan_bug': 'बग स्कैन',
      'ai_chat': 'AI चैट',
      'collection': 'संग्रह',
      'progress': 'प्रगति',
      'history': 'इतिहास',
      'home': 'होम',
      'search_bugs': 'बग खोजें...',
      'identify_bugs': 'बग पहचानें',
      'take_photo': 'फोटो लें',
      'gallery': 'गैलरी',
      'capture_photo': 'बग की फोटो लें',
      'choose_gallery': 'अपनी गैलरी से चुनें',
      'recent_identifications': 'हाल की पहचान',
      'view_all': 'सभी देखें',
      'no_bugs_yet': 'अभी तक कोई बग पहचाना नहीं',
      'no_bugs_identified': 'अभी तक कोई कीट पहचाना नहीं गया है',
      'start_photo': 'एक बग की फोटो लेकर शुरू करें',
      'ai_bug_expert': 'AI बग विशेषज्ञ',
      'entomology_assistant': 'एंटोमोलॉजी सहायक',
      'ask_anything': 'बग और पक्षी के बारे में कुछ भी पूछें!',
      'hello_message': 'नमस्ते! मैं अपना एंटोमॉलॉजी सहायक हूं। आज मैं आपकी कैसे मदद कर सकता हूं?',
      'type_message': 'अपना संदेश टाइप करें...',
      'venomous_tip': 'कई बग और पक्षी दही हो सकते हैं। हमेशा सुरक्षित दूरी बनाएं और अज्ञात प्रकारों को छोड़ दें।',
      'identification_tip': 'सटीक पहचान के लिए शरीर का आकार, रंग पैटर्न, पैरों की संख्या और उँगलियों की जानकारी देखें।',
      'habitat_tip': 'अलग-अलग बग अलग वातावरण को प्राथमिकता देते हैं। वातावरण को जानने से पहचान में मदद मिलती है।',
      'danger_tip': 'कुछ बग और पक्षी खतरनाक हो सकते हैं। हमेशा सुरक्षा को प्राथमिकता दें और सीधे स्पर्श से बचें।',
      'disease_tip': 'कुछ बग रोग ले सकते हैं। अपने क्षेत्र में संभावित स्वास्थ्य खतरों के बारे में जानें।',
      'safety_tip': 'जब भी अज्ञात बग या पक्षी मिलते हैं, दूरी से देखें और उन्हें उत्साहित करने से बचें।',
      'general_help': 'मैं बग पहचान, दही मूल्यांकन, वातावरण जानकारी और सुरक्षा टिप्स के बारे में मदद कर सकता हूं। आप किस विषय के बारे में और जानना चाहते हैं?',
      'bug_fact_of_day': 'बग का दिन का विशेषज्ञ',
      'bug_fact_content': 'दुनिया में 1 मिलियन से अधिक ज्ञात बग प्रकार हैं, जो इसे पृथ्वी पर सबसे विविध जानवर समूह बनाते हैं!',
      'danger_level': 'खतरनाक स्तर',
      'description': 'विवरण',
      'venomous': 'दही',
      'species': 'प्रकार',
      'habitat': 'वातावरण',
      'diseases': 'रोग',
      'safety_tips': 'सुरक्षा टिप्स',
      'high_danger': 'उच्च खतरनाक',
      'medium_danger': 'मध्यम खतरनाक',
      'low_danger': 'कम खतरनाक',
      'yes': 'हाँ',
      'no': 'नहीं',
      'unknown': 'अज्ञात',
      'analyzing': 'विश्लेषण हो रहा है...',
      'analysis_complete': 'विश्लेषण पूर्ण',
      'error_occurred': 'एक त्रुटि हुई',
      'try_again': 'पुनः प्रयास करें',
      'share_result': 'परिणाम साझा करें',
      'save_to_gallery': 'गैलरी में सहेजें',
      'delete_record': 'रिकॉर्ड हटाएं',
      'confirm_delete': 'क्या आप वाकई इस रिकॉर्ड को हटाना चाहते हैं?',
      'cancel': 'रद्द करें',
      'delete': 'हटाएं',
      'no_records_found': 'रिकॉर्ड नहीं मिले',
      'scan_new_bug': 'नया बग स्कैन',
      'dangerous_species': 'खतरनाक प्रकार',
      'safe_species': 'सुरक्षित प्रकार',
      'venomous_species': 'दही प्रकार',
      'non_venomous': 'दही नहीं',
      'common_habitats': 'सामान्य वातावरण',
      'prevention_tips': 'रोकथानी टिप्स',
      'emergency_contact': 'आपातकालीन संपर्क',
      'medical_attention': 'यदि चूहा हो तो चिकित्सा ध्यान दें',
      'keep_distance': 'सुरक्षित दूरी बनाएं',
      'do_not_touch': 'छूने और संभालने से बचें',
      'call_expert': 'एक स्थानीय विशेषज्ञ को कॉल करें',
      'insect_identification': 'बग पहचान',
      'reptile_identification': 'पक्षी पहचान',
      'spider_identification': 'चूहा पहचान',
      'snake_identification': 'शंकु पहचान',
      'scorpion_identification': 'अक्रोपिया पहचान',
      'beetle_identification': 'बग पहचान',
      'butterfly_identification': 'मंजिल पहचान',
      'ant_identification': 'चूहा पहचान',
      'bee_identification': 'बी पहचान',
      'wasp_identification': 'वास्प पहचान',
      'mosquito_identification': 'चूहा पहचान',
      'tick_identification': 'टिक पहचान',
      'centipede_identification': 'सैंसिलिया पहचान',
      'millipede_identification': 'मिलिसिलिया पहचान',
      'cricket_identification': 'क्रिकेट पहचान',
      'grasshopper_identification': 'ग्रास्पर पहचान',
      'ladybug_identification': 'चूहा पहचान',
      'dragonfly_identification': 'यूसुफ पहचान',
      'firefly_identification': 'एटेश पहचान',
      'moth_identification': 'गुवे पहचान',
      'fly_identification': 'चूहा पहचान',
      'flea_identification': 'फ्लेय पहचान',
      'louse_identification': 'बिट पहचान',
      'bedbug_identification': 'बेडबग पहचान',
      'termite_identification': 'टर्मिट पहचान',
      'cockroach_identification': 'हमाम पहचान',
      'earwig_identification': 'हड़पकारी पहचान',
      'silverfish_identification': 'गुदा पहचान',
      'booklice_identification': 'किताब बिट पहचान',
      'springtail_identification': 'स्प्रिंगटेल पहचान',
      'thrips_identification': 'थ्रिप्स पहचान',
      'aphid_identification': 'एफिड पहचान',
      'scale_insect_identification': 'स्केल बिट पहचान',
      'mealybug_identification': 'मेलीबग पहचान',
      'whitefly_identification': 'ब्लेय फ्लेय पहचान',
      'leafhopper_identification': 'फूल पहचान',
      'planthopper_identification': 'प्लांट पहचान',
      'treehopper_identification': 'ट्रीहवे पहचान',
      'cicada_identification': 'सिस्टर पहचान',
      'spittlebug_identification': 'स्पिटल बग पहचान',
      'froghopper_identification': 'फ्रोगहवे पहचान',
      'psyllid_identification': 'प्सिलिड पहचान',
      'bug_identifier': 'कीट पहचानकर्ता',
      'discover_world_of_bugs': 'कीड़ों की दुनिया की खोज करें',
      'bug_fact_1': 'पृथ्वी पर १ मिलियन से अधिक ज्ञात कीट प्रजातियाँ हैं।',
      'bug_fact_2': 'चींटियाँ अपने शरीर के वजन से ५० गुना अधिक उठा सकती हैं।',
      'bug_fact_3': 'ड्रैगनफ्लाई ६० किमी/घंटा तक उड़ सकती हैं, जो सबसे तेज कीटों में से एक है।',
      'bug_fact_4': 'मधुमक्खियाँ नाचकर एक-दूसरे से संवाद करती हैं।',
      'bug_fact_5': 'तितलियाँ अपने पैरों से स्वाद लेती हैं।',
      'bug_fact_6': 'कुछ भृंग, जैसे जुगनू, अंधेरे में चमक सकते हैं।',
      'bug_fact_7': 'मच्छर उन लोगों की ओर आकर्षित होते हैं जिन्होंने अभी केले खाए हैं।',
      'bug_fact_8': 'एक तिलचट्टा अपने सिर के बिना एक सप्ताह तक जीवित रह सकता है।',
      'bug_fact_9': 'लेडीबग अपने जीवनकाल में ५,००० एफिड्स खा सकती है।',
      'bug_fact_10': 'दीमक कभी नहीं सोती और २४ घंटे काम कर सकती है।',
      'bug_fact_11': 'दुनिया का सबसे बड़ा कीट गोलियत बीटल है।',
      'bug_fact_12': 'कुछ तितलियाँ हर साल हजारों किलोमीटर प्रवास करती हैं।',
      'bug_fact_13': 'प्रेइंग मैन्टिस अपना सिर १८० डिग्री घुमा सकती है।',
      'bug_fact_14': 'पिस्सू अपने शरीर की लंबाई से २०० गुना कूद सकते हैं।',
      'bug_fact_15': 'स्टिक कीड़े टहनियों और पत्तियों के साथ पूरी तरह से छिप सकते हैं।',
      'bug_fact_16': 'मधु कभी खराब नहीं होता, मधुमक्खियों के एंजाइम के कारण।',
      'bug_fact_17': 'कुछ चींटियाँ भोजन के लिए कवक उगाती हैं।',
      'bug_fact_18': 'सिकाडा १७ साल तक भूमिगत रह सकते हैं।',
      'bug_fact_19': 'फायर एंट्स बाढ़ से बचने के लिए जीवित बेड़े बना सकती हैं।',
      'bug_fact_20': 'बम बीटल खुद को गर्म रसायन छोड़कर बचाता है।',
    },
    'ar': {
      'select_language': 'اختر اللغة',
      'choose_your_language': 'اختر اللغة المفضلة لديك',
      'continue': 'استمرار',
      'bug_scanner': 'منفصل الباحث',
      'discover_world_of_insects': 'اكتشف عالم الحشرات والزواحف',
      'ai_powered': 'تمت إضافة الذكاء الاصطناعي',
      'instant_results': 'النتائج الفورية',
      'initializing': 'جاري التهيئة...',
      'scan_bug': 'مسح الباحث',
      'ai_chat': 'دردشة AI',
      'collection': 'جمع',
      'progress': 'التقدم',
      'history': 'التاريخ',
      'home': 'الصفحة الرئيسية',
      'search_bugs': 'البحث عن الحشرات...',
      'identify_bugs': 'تحديد الحشرات',
      'take_photo': 'إلتقط الصورة',
      'gallery': 'المعرض',
      'capture_photo': 'التقط صورة للحشرة',
      'choose_gallery': 'اختر من صورك',
      'recent_identifications': 'التحديدات الأخيرة',
      'view_all': 'عرض الكل',
      'no_bugs_yet': 'لم يتم تحديد أي حشرات بعد',
      'no_bugs_identified': 'لم يتم تحديد أي حشرات بعد',
      'start_photo': 'ابدأ بإلتقاط صورة لحشرة',
      'ai_bug_expert': 'خبير الباحث الذكاء الاصطناعي',
      'entomology_assistant': 'مساعد الأنتومولوجيا',
      'ask_anything': 'اسألني أي شيء عن الحشرات والزواحف!',
      'hello_message': 'مرحباً! أنا مساعدك في الأنتومولوجيا. كيف يمكنني مساعدتك اليوم؟',
      'type_message': 'اكتب رسالتك...',
      'venomous_tip': 'العديد من الحشرات والزواحف يمكن أن تكون سامة. الحفاظ على المسافة الآمنة وتجنب التعامل مع الأنواع غير المعروفة.',
      'identification_tip': 'اطلع على الميزات الأساسية مثل شكل الجسم والأنماط اللونية وعدد القدمين والأنفاس لتحديد دقيق.',
      'habitat_tip': 'الحشرات تفضل الأماكن المختلفة. معرفة البيئة يمكن أن تساعد في التحديد.',
      'danger_tip': 'بعض الحشرات والزواحف يمكن أن تكون خطيرة. الأولوية الأولى للأمان وتجنب التلامس المباشر.',
      'disease_tip': 'بعض الحشرات يمكن أن تحمل الأمراض. كن على علم بالمخاطر الصحية المحتملة في منطقتك.',
      'safety_tip': 'عندما تواجه حشرات أو زواحف غير معروفة، انظر من مسافة وتجنب التحفيز.',
      'general_help': 'يمكنني مساعدتك في تحديد الحشرات، تقييم السموم، معلومات عن البيئة، ونصائح الأمان. ما هو الموضوع الذي ترغب في معرفة المزيد عنه؟',
      'bug_fact_of_day': 'حقيقة الباحث لليوم',
      'bug_fact_content': 'هناك أكثر من مليون نوع معروف من الحشرات، مما يجعلهم أكبر مجموعة من الحيوانات في الأرض!',
      'danger_level': 'مستوى الخطر',
      'description': 'الوصف',
      'venomous': 'سام',
      'species': 'النوع',
      'habitat': 'البيئة',
      'diseases': 'الأمراض',
      'safety_tips': 'نصائح الأمان',
      'high_danger': 'خطر عالي',
      'medium_danger': 'خطر متوسط',
      'low_danger': 'خطر منخفض',
      'yes': 'نعم',
      'no': 'لا',
      'unknown': 'غير معروف',
      'analyzing': 'يتم التحليل...',
      'analysis_complete': 'التحليل المكتمل',
      'error_occurred': 'حدث خطأ',
      'try_again': 'حاول مرة أخرى',
      'share_result': 'مشاركة النتيجة',
      'save_to_gallery': 'حفظ في المعرض',
      'delete_record': 'حذف السجل',
      'confirm_delete': 'هل أنت متأكد من حذف هذا السجل؟',
      'cancel': 'إلغاء',
      'delete': 'حذف',
      'no_records_found': 'لم يتم العثور على سجلات',
      'scan_new_bug': 'مسح حشرة جديدة',
      'dangerous_species': 'الأنواع الخطرة',
      'safe_species': 'الأنواع الآمنة',
      'venomous_species': 'الأنواع السامة',
      'non_venomous': 'غير سام',
      'common_habitats': 'البيئات الشائعة',
      'prevention_tips': 'نصائح الوقاية',
      'emergency_contact': 'اتصال الطوارئ',
      'medical_attention': 'التركيز على الرعاية الطبية إذا تم خلعه',
      'keep_distance': 'الحفاظ على المسافة الآمنة',
      'do_not_touch': 'لا تلمس أو تتعامل مع',
      'call_expert': 'اتصل بخبير محلي',
      'insect_identification': 'تحديد الحشرات',
      'reptile_identification': 'تحديد الزواحف',
      'spider_identification': 'تحديد العناكب',
      'snake_identification': 'تحديد الأفعى',
      'scorpion_identification': 'تحديد العقرب',
      'beetle_identification': 'تحديد البرغوث',
      'butterfly_identification': 'تحديد الفراشات',
      'ant_identification': 'تحديد النملة',
      'bee_identification': 'تحديد النحلة',
      'wasp_identification': 'تحديد العسل',
      'mosquito_identification': 'تحديد الطائر',
      'tick_identification': 'تحديد الطائر',
      'centipede_identification': 'تحديد الأفعى العشرية',
      'millipede_identification': 'تحديد الأفعى الثنائية',
      'cricket_identification': 'تحديد الأفعى الطائرة',
      'grasshopper_identification': 'تحديد الأفعى الطائرة',
      'ladybug_identification': 'تحديد النملة الأزرق',
      'dragonfly_identification': 'تحديد الطائر الأزرق',
      'firefly_identification': 'تحديد الطائر الأضواء',
      'moth_identification': 'تحديد الطائر',
      'fly_identification': 'تحديد الطائر',
      'flea_identification': 'تحديد الطائر',
      'louse_identification': 'تحديد الطائر',
      'bedbug_identification': 'تحديد الطائر',
      'termite_identification': 'تحديد الطائر',
      'cockroach_identification': 'تحديد الطائر',
      'earwig_identification': 'تحديد الطائر',
      'silverfish_identification': 'تحديد الطائر',
      'booklice_identification': 'تحديد الطائر',
      'springtail_identification': 'تحديد الطائر',
      'thrips_identification': 'تحديد الطائر',
      'aphid_identification': 'تحديد الطائر',
      'scale_insect_identification': 'تحديد الطائر',
      'mealybug_identification': 'تحديد الطائر',
      'whitefly_identification': 'تحديد الطائر',
      'leafhopper_identification': 'تحديد الطائر',
      'planthopper_identification': 'تحديد الطائر',
      'treehopper_identification': 'تحديد الطائر',
      'cicada_identification': 'تحديد الطائر',
      'spittlebug_identification': 'تحديد الطائر',
      'froghopper_identification': 'تحديد الطائر',
      'psyllid_identification': 'تحديد الطائر',
      'bug_identifier': 'مُعرّف الحشرات',
      'discover_world_of_bugs': 'اكتشف عالم الحشرات',
      'bug_fact_1': 'هناك أكثر من مليون نوع معروف من الحشرات على الأرض.',
      'bug_fact_2': 'يمكن للنمل رفع أشياء تزن ٥٠ ضعف وزن جسمه.',
      'bug_fact_3': 'اليعسوب يمكن أن يطير بسرعة تصل إلى ٦٠ كم/ساعة، من أسرع الحشرات.',
      'bug_fact_4': 'تتواصل النحل مع بعضها البعض من خلال الرقص.',
      'bug_fact_5': 'الفراشات تتذوق بأقدامها.',
      'bug_fact_6': 'بعض الخنافس يمكن أن تتوهج في الظلام مثل اليراعات.',
      'bug_fact_7': 'تنجذب البعوض إلى الأشخاص الذين أكلوا الموز للتو.',
      'bug_fact_8': 'يمكن للصراصير أن تعيش لمدة أسبوع بدون رأسها.',
      'bug_fact_9': 'يمكن ليرقات الدعسوقة أن تأكل حتى ٥٠٠٠ من المن في حياتها.',
      'bug_fact_10': 'النمل الأبيض لا ينام أبدًا ويمكنه العمل ٢٤ ساعة في اليوم.',
      'bug_fact_11': 'أكبر حشرة في العالم هي خنفساء الجالوت.',
      'bug_fact_12': 'بعض الفراشات تهاجر آلاف الكيلومترات كل عام.',
      'bug_fact_13': 'فرس النبي يمكنه تدوير رأسه ١٨٠ درجة.',
      'bug_fact_14': 'البراغيث يمكنها القفز ٢٠٠ مرة طول جسمها.',
      'bug_fact_15': 'حشرات العصا يمكن أن تتنكر كالأغصان والأوراق.',
      'bug_fact_16': 'العسل لا يفسد أبدًا بفضل إنزيمات النحل.',
      'bug_fact_17': 'بعض النمل يزرع الفطريات للطعام.',
      'bug_fact_18': 'السيكادا يمكن أن تعيش تحت الأرض لمدة تصل إلى ١٧ عامًا.',
      'bug_fact_19': 'النمل الناري يمكن أن يشكل طوافات حية للبقاء على قيد الحياة أثناء الفيضانات.',
      'bug_fact_20': 'خنفساء القاذف تدافع عن نفسها بإطلاق مواد كيميائية ساخنة.',
    },
    'id': {
      'select_language': 'Pilih Bahasa',
      'choose_your_language': 'Pilih bahasa favorit Anda',
      'continue': 'Lanjutkan',
      'bug_scanner': 'Pemindaian Serangga',
      'discover_world_of_insects': 'Jelajahi Dunia Serangga & Reptil',
      'ai_powered': 'Dukungan AI',
      'instant_results': 'Hasil Instan',
      'initializing': 'Menginisialisasi...',
      'scan_bug': 'Pemindaian Serangga',
      'ai_chat': 'Chat AI',
      'collection': 'Koleksi',
      'progress': 'Progres',
      'history': 'Riwayat',
      'home': 'Beranda',
      'search_bugs': 'Cari serangga...',
      'identify_bugs': 'Identifikasi Serangga',
      'take_photo': 'Ambil Foto',
      'gallery': 'Galeri',
      'capture_photo': 'Ambil foto serangga',
      'choose_gallery': 'Pilih dari galeri Anda',
      'recent_identifications': 'Identifikasi Terbaru',
      'view_all': 'Lihat Semua',
      'no_bugs_yet': 'Belum ada serangga yang diidentifikasi',
      'no_bugs_identified': 'Belum ada serangga yang diidentifikasi',
      'start_photo': 'Mulai dengan mengambil foto serangga',
      'ai_bug_expert': 'Ahli Serangga AI',
      'entomology_assistant': 'Asisten Entomologi',
      'ask_anything': 'Tanyakan apa saja tentang serangga dan reptil!',
      'hello_message': 'Halo! Saya adalah asisten entomologi Anda. Bagaimana saya bisa membantu Anda hari ini?',
      'type_message': 'Tulis pesan Anda...',
      'venomous_tip': 'Banyak serangga dan reptil dapat berbahaya. Selalu jaga jarak yang aman dan hindari menangani spesies yang tidak dikenal.',
      'identification_tip': 'Perhatikan fitur-fitur penting seperti bentuk tubuh, pola warna, jumlah kaki, dan antena untuk identifikasi yang akurat.',
      'habitat_tip': 'Serangga memiliki habitat yang berbeda. Mengetahui habitat dapat membantu identifikasi.',
      'danger_tip': 'Beberapa serangga dan reptil dapat berbahaya. Prioritaskan keamanan dan hindari sentuhan langsung.',
      'disease_tip': 'Beberapa serangga dapat membawa penyakit. Tetap waspada terhadap risiko kesehatan potensial di daerah Anda.',
      'safety_tip': 'Ketika Anda menemukan serangga atau reptil yang tidak dikenal, amati dari jarak dan hindari menggoda mereka.',
      'general_help': 'Saya dapat membantu Anda dengan identifikasi serangga, evaluasi racun, informasi habitat, dan tips keamanan. Apa topik yang ingin Anda ketahui lebih lanjut?',
      'bug_fact_of_day': 'Fakta Serangga Hari Ini',
      'bug_fact_content': 'Ada lebih dari 1 juta spesies serangga yang dikenal, yang membuat mereka kelompok hewan terbanyak di Bumi!',
      'danger_level': 'Tingkat Bahaya',
      'description': 'Deskripsi',
      'venomous': 'Berbahaya',
      'species': 'Spesies',
      'habitat': 'Habitat',
      'diseases': 'Penyakit',
      'safety_tips': 'Tips Keamanan',
      'high_danger': 'Tingkat Bahaya Tinggi',
      'medium_danger': 'Tingkat Bahaya Sedang',
      'low_danger': 'Tingkat Bahaya Rendah',
      'yes': 'Ya',
      'no': 'Tidak',
      'unknown': 'Tidak Diketahui',
      'analyzing': 'Menganalisis...',
      'analysis_complete': 'Analisis Selesai',
      'error_occurred': 'Terjadi kesalahan',
      'try_again': 'Coba Lagi',
      'share_result': 'Bagikan Hasil',
      'save_to_gallery': 'Simpan ke Galeri',
      'delete_record': 'Hapus Catatan',
      'confirm_delete': 'Apakah Anda yakin ingin menghapus catatan ini?',
      'cancel': 'Batal',
      'delete': 'Hapus',
      'no_records_found': 'Tidak ada catatan yang ditemukan',
      'scan_new_bug': 'Pemindaian Serangga Baru',
      'dangerous_species': 'Spesies Berbahaya',
      'safe_species': 'Spesies Aman',
      'venomous_species': 'Spesies Berbahaya',
      'non_venomous': 'Tidak Berbahaya',
      'common_habitats': 'Habitat Umum',
      'prevention_tips': 'Tips Pencegahan',
      'emergency_contact': 'Kontak Darurat',
      'medical_attention': 'Berikan perhatian medis jika tertusuk',
      'keep_distance': 'Jaga jarak yang aman',
      'do_not_touch': 'Jangan sentuh atau tangani',
      'call_expert': 'Hubungi ahli lokal',
      'insect_identification': 'Identifikasi Serangga',
      'reptile_identification': 'Identifikasi Reptil',
      'spider_identification': 'Identifikasi Laba-laba',
      'snake_identification': 'Identifikasi Ular',
      'scorpion_identification': 'Identifikasi Ular',
      'beetle_identification': 'Identifikasi Kumbang',
      'butterfly_identification': 'Identifikasi Kupu-kupu',
      'ant_identification': 'Identifikasi Lebah',
      'bee_identification': 'Identifikasi Lebah',
      'wasp_identification': 'Identifikasi Lebah',
      'mosquito_identification': 'Identifikasi Nyamuk',
      'tick_identification': 'Identifikasi Nyamuk',
      'centipede_identification': 'Identifikasi Serangga',
      'millipede_identification': 'Identifikasi Serangga',
      'cricket_identification': 'Identifikasi Serangga',
      'grasshopper_identification': 'Identifikasi Serangga',
      'ladybug_identification': 'Identifikasi Lebah',
      'dragonfly_identification': 'Identifikasi Lebah',
      'firefly_identification': 'Identifikasi Lebah',
      'moth_identification': 'Identifikasi Lebah',
      'fly_identification': 'Identifikasi Lebah',
      'flea_identification': 'Identifikasi Lebah',
      'louse_identification': 'Identifikasi Lebah',
      'bedbug_identification': 'Identifikasi Lebah',
      'termite_identification': 'Identifikasi Lebah',
      'cockroach_identification': 'Identifikasi Lebah',
      'earwig_identification': 'Identifikasi Lebah',
      'silverfish_identification': 'Identifikasi Lebah',
      'booklice_identification': 'Identifikasi Lebah',
      'springtail_identification': 'Identifikasi Lebah',
      'thrips_identification': 'Identifikasi Lebah',
      'aphid_identification': 'Identifikasi Lebah',
      'scale_insect_identification': 'Identifikasi Lebah',
      'mealybug_identification': 'Identifikasi Lebah',
      'whitefly_identification': 'Identifikasi Lebah',
      'leafhopper_identification': 'Identifikasi Lebah',
      'planthopper_identification': 'Identifikasi Lebah',
      'treehopper_identification': 'Identifikasi Lebah',
      'cicada_identification': 'Identifikasi Lebah',
      'spittlebug_identification': 'Identifikasi Lebah',
      'froghopper_identification': 'Identifikasi Lebah',
      'psyllid_identification': 'Identifikasi Lebah',
      'bug_identifier': 'Pengenal Serangga',
      'discover_world_of_bugs': 'Jelajahi Dunia Serangga',
      'bug_fact_1': 'Ada lebih dari 1 juta spesies serangga yang diketahui di Bumi.',
      'bug_fact_2': 'Semut dapat mengangkat benda 50 kali berat tubuhnya.',
      'bug_fact_3': 'Capung dapat terbang hingga 60 km/jam, termasuk serangga tercepat.',
      'bug_fact_4': 'Lebah berkomunikasi dengan menari.',
      'bug_fact_5': 'Kupu-kupu merasakan dengan kakinya.',
      'bug_fact_6': 'Beberapa kumbang dapat bersinar dalam gelap seperti kunang-kunang.',
      'bug_fact_7': 'Nyamuk tertarik pada orang yang baru saja makan pisang.',
      'bug_fact_8': 'Kecoa dapat hidup selama seminggu tanpa kepala.',
      'bug_fact_9': 'Kepik dapat memakan hingga 5.000 kutu daun sepanjang hidupnya.',
      'bug_fact_10': 'Rayap tidak pernah tidur dan dapat bekerja 24 jam sehari.',
      'bug_fact_11': 'Serangga terbesar di dunia adalah kumbang Goliath.',
      'bug_fact_12': 'Beberapa kupu-kupu bermigrasi ribuan kilometer setiap tahun.',
      'bug_fact_13': 'Belalang sembah dapat memutar kepalanya 180 derajat.',
      'bug_fact_14': 'Kutu dapat melompat 200 kali panjang tubuhnya.',
      'bug_fact_15': 'Serangga tongkat dapat menyatu sempurna dengan ranting dan daun.',
      'bug_fact_16': 'Madu tidak pernah basi berkat enzim dari lebah.',
      'bug_fact_17': 'Beberapa semut membudidayakan jamur untuk makanan.',
      'bug_fact_18': 'Jangkrik dapat hidup di bawah tanah hingga 17 tahun.',
      'bug_fact_19': 'Semut api dapat membentuk rakit hidup untuk bertahan dari banjir.',
      'bug_fact_20': 'Kumbang penembak membela diri dengan menyemprotkan bahan kimia panas.',
    },
    'vi': {
      'select_language': 'Chọn ngôn ngữ',
      'choose_your_language': 'Chọn ngôn ngữ yêu thích của bạn',
      'continue': 'Tiếp tục',
      'bug_scanner': 'Máy quét bọ',
      'discover_world_of_insects': 'Khám phá thế giới côn trùng & bò sát',
      'ai_powered': 'Hỗ trợ AI',
      'instant_results': 'Kết quả ngay lập tức',
      'initializing': 'Đang khởi tạo...',
      'scan_bug': 'Quét bọ',
      'ai_chat': 'Tin nhắn AI',
      'collection': 'Bộ sưu tập',
      'progress': 'Tiến độ',
      'history': 'Lịch sử',
      'home': 'Trang chủ',
      'search_bugs': 'Tìm kiếm côn trùng...',
      'identify_bugs': 'Nhận dạng côn trùng',
      'take_photo': 'Chụp ảnh',
      'gallery': 'Thư viện',
      'capture_photo': 'Chụp ảnh côn trùng',
      'choose_gallery': 'Chọn từ thư viện của bạn',
      'recent_identifications': 'Nhận dạng gần đây',
      'view_all': 'Xem tất cả',
      'no_bugs_yet': 'Chưa có côn trùng nào được nhận dạng',
      'no_bugs_identified': 'Chưa có côn trùng nào được nhận dạng',
      'start_photo': 'Bắt đầu bằng cách chụp ảnh một con côn trùng',
      'ai_bug_expert': 'Chuyên gia bọ AI',
      'entomology_assistant': 'Trợ lý Entomology',
      'ask_anything': 'Hỏi tôi bất cứ điều gì về côn trùng & bò sát!',
      'hello_message': 'Xin chào! Tôi là trợ lý Entomology của bạn. Tôi có thể giúp bạn như thế nào hôm nay?',
      'type_message': 'Nhập tin nhắn của bạn...',
      'venomous_tip': 'Nhiều loại côn trùng & bò sát có thể độc. Luôn giữ khoảng cách an toàn và tránh xử lý các loài không xác định.',
      'identification_tip': 'Hãy quan sát các đặc điểm chính như hình dạng cơ thể, mẫu màu sắc, số chân và râu để nhận dạng chính xác.',
      'habitat_tip': 'Các loại côn trùng có nhu cầu về môi trường khác nhau. Biết về môi trường có thể giúp nhận dạng.',
      'danger_tip': 'Một số côn trùng & bò sát có thể nguy hiểm. Luôn ưu tiên an toàn và tránh tiếp xúc trực tiếp.',
      'disease_tip': 'Một số côn trùng có thể lây truyền bệnh. Luôn luôn cẩn thận về những nguy cơ sức khỏe tiềm ẩn trong khu vực của bạn.',
      'safety_tip': 'Khi gặp côn trùng hoặc bò sát không xác định, hãy quan sát từ xa và tránh kích thích chúng.',
      'general_help': 'Tôi có thể giúp bạn về nhận dạng côn trùng, đánh giá độc, thông tin về môi trường và mẹo an toàn. Bạn muốn biết thêm về chủ đề nào?',
      'bug_fact_of_day': 'Sự thật về côn trùng ngày hôm nay',
      'bug_fact_content': 'Có hơn 1 triệu loài côn trùng đã được biết đến, làm cho chúng là nhóm động vật phong phú nhất trên Trái đất!',
      'danger_level': 'Mức độ nguy hiểm',
      'description': 'Mô tả',
      'venomous': 'Độc',
      'species': 'Loài',
      'habitat': 'Môi trường',
      'diseases': 'Bệnh',
      'safety_tips': 'Mẹo an toàn',
      'high_danger': 'Nguy hiểm cao',
      'medium_danger': 'Nguy hiểm trung bình',
      'low_danger': 'Nguy hiểm thấp',
      'yes': 'Có',
      'no': 'Không',
      'unknown': 'Không xác định',
      'analyzing': 'Đang phân tích...',
      'analysis_complete': 'Phân tích hoàn tất',
      'error_occurred': 'Đã xảy ra lỗi',
      'try_again': 'Thử lại',
      'share_result': 'Chia sẻ kết quả',
      'save_to_gallery': 'Lưu vào thư viện',
      'delete_record': 'Xóa bản ghi',
      'confirm_delete': 'Bạn có chắc chắn muốn xóa bản ghi này không?',
      'cancel': 'Hủy bỏ',
      'delete': 'Xóa',
      'no_records_found': 'Không tìm thấy bản ghi nào',
      'scan_new_bug': 'Quét côn trùng mới',
      'dangerous_species': 'Loài nguy hiểm',
      'safe_species': 'Loài an toàn',
      'venomous_species': 'Loài độc',
      'non_venomous': 'Không độc',
      'common_habitats': 'Môi trường phổ biến',
      'prevention_tips': 'Mẹo phòng ngừa',
      'emergency_contact': 'Liên hệ khẩn cấp',
      'medical_attention': 'Điều trị y tế nếu bị cắn',
      'keep_distance': 'Giữ khoảng cách an toàn',
      'do_not_touch': 'Đừng chạm hoặc xử lý',
      'call_expert': 'Gọi chuyên gia địa phương',
      'insect_identification': 'Nhận dạng côn trùng',
      'reptile_identification': 'Nhận dạng bò sát',
      'spider_identification': 'Nhận dạng tôm',
      'snake_identification': 'Nhận dạng rắn',
      'scorpion_identification': 'Nhận dạng rắn',
      'beetle_identification': 'Nhận dạng bọ',
      'butterfly_identification': 'Nhận dạng bướm',
      'ant_identification': 'Nhận dạng kiến',
      'bee_identification': 'Nhận dạng ong',
      'wasp_identification': 'Nhận dạng ong',
      'mosquito_identification': 'Nhận dạng muỗi',
      'tick_identification': 'Nhận dạng muỗi',
      'centipede_identification': 'Nhận dạng gián',
      'millipede_identification': 'Nhận dạng gián',
      'cricket_identification': 'Nhận dạng còi',
      'grasshopper_identification': 'Nhận dạng còi',
      'ladybug_identification': 'Nhận dạng kiến',
      'dragonfly_identification': 'Nhận dạng bướm',
      'firefly_identification': 'Nhận dạng bướm',
      'moth_identification': 'Nhận dạng bướm',
      'fly_identification': 'Nhận dạng muỗi',
      'flea_identification': 'Nhận dạng muỗi',
      'louse_identification': 'Nhận dạng muỗi',
      'bedbug_identification': 'Nhận dạng muỗi',
      'termite_identification': 'Nhận dạng muỗi',
      'cockroach_identification': 'Nhận dạng muỗi',
      'earwig_identification': 'Nhận dạng muỗi',
      'silverfish_identification': 'Nhận dạng muỗi',
      'booklice_identification': 'Nhận dạng muỗi',
      'springtail_identification': 'Nhận dạng muỗi',
      'thrips_identification': 'Nhận dạng muỗi',
      'aphid_identification': 'Nhận dạng muỗi',
      'scale_insect_identification': 'Nhận dạng muỗi',
      'mealybug_identification': 'Nhận dạng muỗi',
      'whitefly_identification': 'Nhận dạng muỗi',
      'leafhopper_identification': 'Nhận dạng muỗi',
      'planthopper_identification': 'Nhận dạng muỗi',
      'treehopper_identification': 'Nhận dạng muỗi',
      'cicada_identification': 'Nhận dạng muỗi',
      'spittlebug_identification': 'Nhận dạng muỗi',
      'froghopper_identification': 'Nhận dạng muỗi',
      'psyllid_identification': 'Nhận dạng muỗi',
      'bug_identifier': 'Pengenal Serangga',
      'discover_world_of_bugs': 'Jelajahi Dunia Serangga',
      'bug_fact_1': 'Có hơn 1 triệu loài côn trùng đã biết trên Trái đất.',
      'bug_fact_2': 'Kiến có thể nâng vật nặng gấp 50 lần trọng lượng cơ thể.',
      'bug_fact_3': 'Chuồn chuồn có thể bay tới 60 km/h, là một trong những côn trùng nhanh nhất.',
      'bug_fact_4': 'Ong giao tiếp với nhau bằng cách nhảy múa.',
      'bug_fact_5': 'Bướm cảm nhận vị bằng chân.',
      'bug_fact_6': 'Một số loài bọ có thể phát sáng trong bóng tối như đom đóm.',
      'bug_fact_7': 'Muỗi bị thu hút bởi người vừa ăn chuối.',
      'bug_fact_8': 'Gián có thể sống một tuần mà không có đầu.',
      'bug_fact_9': 'Bọ rùa có thể ăn tới 5.000 con rệp trong đời.',
      'bug_fact_10': 'Mối không bao giờ ngủ và có thể làm việc 24 giờ mỗi ngày.',
      'bug_fact_11': 'Côn trùng lớn nhất thế giới là bọ cánh cứng Goliath.',
      'bug_fact_12': 'Một số loài bướm di cư hàng ngàn km mỗi năm.',
      'bug_fact_13': 'Bọ ngựa có thể quay đầu 180 độ.',
      'bug_fact_14': 'Bọ chét có thể nhảy xa gấp 200 lần chiều dài cơ thể.',
      'bug_fact_15': 'Bọ que có thể ngụy trang hoàn hảo với cành cây và lá.',
      'bug_fact_16': 'Mật ong không bao giờ hỏng nhờ enzyme của ong.',
      'bug_fact_17': 'Một số loài kiến nuôi nấm để làm thức ăn.',
      'bug_fact_18': 'Ve sầu có thể sống dưới đất tới 17 năm.',
      'bug_fact_19': 'Kiến lửa có thể tạo thành bè sống để sống sót qua lũ lụt.',
      'bug_fact_20': 'Bọ pháo thủ tự vệ bằng cách phun hóa chất nóng.',
    },
    'ko': {
      'select_language': '언어 선택',
      'choose_your_language': '선호하는 언어를 선택하세요',
      'continue': '계속하기',
      'bug_scanner': '벌레 스캐너',
      'discover_world_of_insects': '벌레와 파충류 세계 발견하기',
      'ai_powered': 'AI 지원',
      'instant_results': '즉각적인 결과',
      'initializing': '초기화 중...',
      'scan_bug': '벌레 스캔',
      'ai_chat': 'AI 채팅',
      'collection': '수집',
      'progress': '진행',
      'history': '기록',
      'home': '홈',
      'search_bugs': '벌레 검색...',
      'identify_bugs': '벌레 식별',
      'take_photo': '사진 찍기',
      'gallery': '갤러리',
      'capture_photo': '벌레 사진 찍기',
      'choose_gallery': '갤러리에서 선택',
      'recent_identifications': '최근 식별',
      'view_all': '모두 보기',
      'no_bugs_yet': '아직 벌레가 식별되지 않았습니다',
      'no_bugs_identified': '아직 식별된 벌레가 없습니다',
      'start_photo': '벌레 사진을 찍어 시작하세요',
      'ai_bug_expert': 'AI 벌레 전문가',
      'entomology_assistant': '곤충학 도우미',
      'ask_anything': '벌레와 파충류에 대해 무엇이든 물어보세요!',
      'hello_message': '안녕하세요! 저는 곤충학 도우미입니다. 오늘 제가 어떻게 도와드릴까요?',
      'type_message': '메시지를 입력하세요...',
      'venomous_tip': '많은 벌레와 파충류는 독성이 있을 수 있습니다. 항상 안전한 거리를 유지하고 알 수 없는 종류는 다루지 마세요.',
      'identification_tip': '정확한 식별을 위해 몸 모양, 색상 패턴, 다리 수, 귀 등의 주요 특징을 찾으세요.',
      'habitat_tip': '벌레들은 다른 환경을 선호합니다. 서식지를 알면 식별에 도움이 됩니다.',
      'danger_tip': '몇몇 벌레와 파충류는 위험할 수 있습니다. 항상 안전을 우선하고 직접 접촉을 피하세요.',
      'disease_tip': '몇몇 벌레는 질병을 옮길 수 있습니다. 당신의 지역에 대한 잠재적 건강 위험에 대해 주의하세요.',
      'safety_tip': '알 수 없는 벌레나 파충류를 만났을 때, 멀리서 관찰하고 그들을 자극하지 마세요.',
      'general_help': '벌레 식별, 독성 평가, 서식지 정보, 안전 팁에 대해 도와드릴 수 있습니다. 어떤 주제에 대해 더 알고 싶으세요?',
      'bug_fact_of_day': '벌레 날짜 팩트',
      'bug_fact_content': '지구상에 100만 종 이상의 벌레가 알려져 있으며, 이는 지구상 가장 다양한 동물 종을 만듭니다!',
      'danger_level': '위험 수준',
      'description': '설명',
      'venomous': '독성',
      'species': '종',
      'habitat': '서식지',
      'diseases': '질병',
      'safety_tips': '안전 팁',
      'high_danger': '높은 위험',
      'medium_danger': '중간 위험',
      'low_danger': '낮은 위험',
      'yes': '네',
      'no': '아니오',
      'unknown': '알 수 없음',
      'analyzing': '분석 중...',
      'analysis_complete': '분석 완료',
      'error_occurred': '오류 발생',
      'try_again': '다시 시도',
      'share_result': '결과 공유',
      'save_to_gallery': '갤러리에 저장',
      'delete_record': '기록 삭제',
      'confirm_delete': '이 기록을 삭제하시겠습니까?',
      'cancel': '취소',
      'delete': '삭제',
      'no_records_found': '기록을 찾을 수 없습니다',
      'scan_new_bug': '새 벌레 스캔',
      'dangerous_species': '위험한 종',
      'safe_species': '안전한 종',
      'venomous_species': '독성 종',
      'non_venomous': '비독성',
      'common_habitats': '일반적인 서식지',
      'prevention_tips': '예방 팁',
      'emergency_contact': '비상 연락처',
      'medical_attention': '벌레에 치명적이면 의료 주의',
      'keep_distance': '안전한 거리 유지',
      'do_not_touch': '만지지 마세요 또는 다루지 마세요',
      'call_expert': '지역 전문가 전화',
      'insect_identification': '벌레 식별',
      'reptile_identification': '파충류 식별',
      'spider_identification': '거미 식별',
      'snake_identification': '뱀 식별',
      'scorpion_identification': '전갈 식별',
      'beetle_identification': '벌레 식별',
      'butterfly_identification': '나비 식별',
      'ant_identification': '개미 식별',
      'bee_identification': '벌 식별',
      'wasp_identification': '벌레 식별',
      'mosquito_identification': '벌레 식별',
      'tick_identification': '벌레 식별',
      'centipede_identification': '벌레 식별',
      'millipede_identification': '벌레 식별',
      'cricket_identification': '벌레 식별',
      'grasshopper_identification': '벌레 식별',
      'ladybug_identification': '벌레 식별',
      'dragonfly_identification': '벌레 식별',
      'firefly_identification': '벌레 식별',
      'moth_identification': '벌레 식별',
      'fly_identification': '벌레 식별',
      'flea_identification': '벌레 식별',
      'louse_identification': '벌레 식별',
      'bedbug_identification': '벌레 식별',
      'termite_identification': '벌레 식별',
      'cockroach_identification': '벌레 식별',
      'earwig_identification': '벌레 식별',
      'silverfish_identification': '벌레 식별',
      'booklice_identification': '벌레 식별',
      'springtail_identification': '벌레 식별',
      'thrips_identification': '벌레 식별',
      'aphid_identification': '벌레 식별',
      'scale_insect_identification': '벌레 식별',
      'mealybug_identification': '벌레 식별',
      'whitefly_identification': '벌레 식별',
      'leafhopper_identification': '벌레 식별',
      'planthopper_identification': '벌레 식별',
      'treehopper_identification': '벌레 식별',
      'cicada_identification': '벌레 식별',
      'spittlebug_identification': '벌레 식별',
      'froghopper_identification': '벌레 식별',
      'psyllid_identification': '벌레 식별',
      'bug_identifier': '벌레 식별기',
      'discover_world_of_bugs': '곤충의 세계를 발견하세요',
      'bug_fact_1': '지구에는 100만 종이 넘는 곤충이 있습니다.',
      'bug_fact_2': '개미는 자기 몸무게의 50배를 들어올릴 수 있습니다.',
      'bug_fact_3': '잠자리는 시속 60km까지 날 수 있어 가장 빠른 곤충 중 하나입니다.',
      'bug_fact_4': '벌은 춤을 추며 서로 소통합니다.',
      'bug_fact_5': '나비는 발로 맛을 느낍니다.',
      'bug_fact_6': '일부 딱정벌레는 반딧불이처럼 어둠 속에서 빛날 수 있습니다.',
      'bug_fact_7': '모기는 바나나를 먹은 사람에게 더 끌립니다.',
      'bug_fact_8': '바퀴벌레는 머리 없이도 일주일을 살 수 있습니다.',
      'bug_fact_9': '무당벌레는 평생 5,000마리의 진딧물을 먹을 수 있습니다.',
      'bug_fact_10': '흰개미는 절대 잠을 자지 않고 하루 24시간 일할 수 있습니다.',
      'bug_fact_11': '세계에서 가장 큰 곤충은 골리앗 딱정벌레입니다.',
      'bug_fact_12': '일부 나비는 매년 수천 킬로미터를 이동합니다.',
      'bug_fact_13': '사마귀는 머리를 180도 돌릴 수 있습니다.',
      'bug_fact_14': '벼룩은 몸길이의 200배를 뛸 수 있습니다.',
      'bug_fact_15': '막대벌레는 나뭇가지와 잎에 완벽하게 위장할 수 있습니다.',
      'bug_fact_16': '꿀은 벌의 효소 덕분에 절대 상하지 않습니다.',
      'bug_fact_17': '일부 개미는 먹이를 위해 곰팡이를 재배합니다.',
      'bug_fact_18': '매미는 땅속에서 17년까지 살 수 있습니다.',
      'bug_fact_19': '불개미는 홍수에서 살아남기 위해 살아있는 뗏목을 만들 수 있습니다.',
      'bug_fact_20': '폭격수 딱정벌레는 뜨거운 화학물질을 쏘아 방어합니다.',
    },
    'ja': {
      'select_language': '言語を選択',
      'choose_your_language': 'あなたの好みの言語を選択',
      'continue': '続ける',
      'bug_scanner': 'バグスキャナー',
      'discover_world_of_insects': 'バグと爬虫類の世界を発見',
      'ai_powered': 'AI搭載',
      'instant_results': '即時結果',
      'initializing': '初期化中...',
      'scan_bug': 'バグスキャン',
      'ai_chat': 'AIチャット',
      'collection': 'コレクション',
      'progress': '進捗',
      'history': '履歴',
      'home': 'ホーム',
      'search_bugs': 'バグを検索...',
      'identify_bugs': 'バグを識別',
      'take_photo': '写真を撮る',
      'gallery': 'ギャラリー',
      'capture_photo': 'バグの写真を撮る',
      'choose_gallery': 'ギャラリーから選択',
      'recent_identifications': '最近の識別',
      'view_all': 'すべて表示',
      'no_bugs_yet': 'まだバグが識別されていません',
      'no_bugs_identified': 'まだバグが識別されていません',
      'start_photo': 'バグの写真を撮って始める',
      'ai_bug_expert': 'AIバグエキスパート',
      'entomology_assistant': 'エントモロジー助手',
      'ask_anything': 'バグと爬虫類について何でも質問してください！',
      'hello_message': 'こんにちは！エントモロジー助手です。今日はどのようにお手伝いできますか？',
      'type_message': 'メッセージを入力してください...',
      'venomous_tip': '多くのバグと爬虫類は毒性がある可能性があります。常に安全な距離を保ち、未知の種類は扱わないでください。',
      'identification_tip': '正確な識別のために、体の形、色のパターン、足の数、触角などの主要な特徴を探してください。',
      'habitat_tip': 'バグは異なる環境を好みます。環境を知ることで識別が容易になります。',
      'danger_tip': 'いくつかのバグと爬虫類は危険な可能性があります。常に安全を優先し、直接接触を避けてください。',
      'disease_tip': 'いくつかのバグは病気を持つ可能性があります。あなたの地域の潜在的な健康リスクに注意してください。',
      'safety_tip': '未知のバグや爬虫類に遭遇した場合は、遠くから観察し、刺激を与えないでください。',
      'general_help': 'バグの識別、毒性評価、環境情報、および安全ヒントについてお手伝いできます。どのトピックについてもっと知りたいですか？',
      'bug_fact_of_day': 'バグの日の事実',
      'bug_fact_content': '地球上に100万以上のバグ種が知られており、これは地球上で最も多様な動物群を作っています！',
      'danger_level': '危険度',
      'description': '説明',
      'venomous': '毒性',
      'species': '種',
      'habitat': '環境',
      'diseases': '病気',
      'safety_tips': '安全ヒント',
      'high_danger': '高危険',
      'medium_danger': '中危険',
      'low_danger': '低危険',
      'yes': 'はい',
      'no': 'いいえ',
      'unknown': '不明',
      'analyzing': '分析中...',
      'analysis_complete': '分析完了',
      'error_occurred': 'エラーが発生しました',
      'try_again': 'もう一度試してください',
      'share_result': '結果を共有',
      'save_to_gallery': 'ギャラリーに保存',
      'delete_record': 'レコードを削除',
      'confirm_delete': 'このレコードを削除しますか？',
      'cancel': 'キャンセル',
      'delete': '削除',
      'no_records_found': 'レコードが見つかりませんでした',
      'scan_new_bug': '新しいバグスキャン',
      'dangerous_species': '危険種',
      'safe_species': '安全種',
      'venomous_species': '毒性種',
      'non_venomous': '非毒性',
      'common_habitats': '一般的な環境',
      'prevention_tips': '予防ヒント',
      'emergency_contact': '緊急連絡',
      'medical_attention': '虫に噛まれた場合は医療注意',
      'keep_distance': '安全な距離を保つ',
      'do_not_touch': '触らないでくださいまたは扱わないでください',
      'call_expert': 'ローカルエキスパートを呼び出す',
      'insect_identification': 'バグを識別',
      'reptile_identification': '爬虫類を識別',
      'spider_identification': 'クモを識別',
      'snake_identification': 'ヘビを識別',
      'scorpion_identification': 'スコーピオンを識別',
      'beetle_identification': 'バグを識別',
      'butterfly_identification': 'バタフライを識別',
      'ant_identification': 'アリを識別',
      'bee_identification': 'ミツバチを識別',
      'wasp_identification': 'バスプを識別',
      'mosquito_identification': 'バスプを識別',
      'tick_identification': 'バスプを識別',
      'centipede_identification': 'センチペディアを識別',
      'millipede_identification': 'ミリシリアを識別',
      'cricket_identification': 'クリケットを識別',
      'grasshopper_identification': 'グラスホッパーを識別',
      'ladybug_identification': 'バタフライを識別',
      'dragonfly_identification': 'バタフライを識別',
      'firefly_identification': 'バタフライを識別',
      'moth_identification': 'バタフライを識別',
      'fly_identification': 'バタフライを識別',
      'flea_identification': 'バタフライを識別',
      'louse_identification': 'バタフライを識別',
      'bedbug_identification': 'バタフライを識別',
      'termite_identification': 'バタフライを識別',
      'cockroach_identification': 'バタフライを識別',
      'earwig_identification': 'バタフライを識別',
      'silverfish_identification': 'バタフライを識別',
      'booklice_identification': 'バタフライを識別',
      'springtail_identification': 'バタフライを識別',
      'thrips_identification': 'バタフライを識別',
      'aphid_identification': 'バタフライを識別',
      'scale_insect_identification': 'バタフライを識別',
      'mealybug_identification': 'バタフライを識別',
      'whitefly_identification': 'バタフライを識別',
      'leafhopper_identification': 'バタフライを識別',
      'planthopper_identification': 'バタフライを識別',
      'treehopper_identification': 'バタフライを識別',
      'cicada_identification': 'バタフライを識別',
      'spittlebug_identification': 'バタフライを識別',
      'froghopper_identification': 'バタフライを識別',
      'psyllid_identification': 'バタフライを識別',
      'bug_identifier': 'バグ識別器',
      'discover_world_of_bugs': '虫の世界を発見する',
      'bug_fact_1': '地球上には100万種以上の昆虫がいます。',
      'bug_fact_2': 'アリは自分の体重の50倍の物を持ち上げることができます。',
      'bug_fact_3': 'トンボは時速60kmで飛ぶことができ、最も速い昆虫の一つです。',
      'bug_fact_4': 'ミツバチはダンスでコミュニケーションを取ります。',
      'bug_fact_5': 'チョウは足で味を感じます。',
      'bug_fact_6': 'ホタルのように暗闇で光る甲虫もいます。',
      'bug_fact_7': '蚊はバナナを食べた人に引き寄せられます。',
      'bug_fact_8': 'ゴキブリは頭がなくても1週間生きられます。',
      'bug_fact_9': 'テントウムシは一生で5,000匹のアブラムシを食べます。',
      'bug_fact_10': 'シロアリは決して眠らず、1日24時間働くことができます。',
      'bug_fact_11': '世界最大の昆虫はゴライアスオオツノハナムグリです。',
      'bug_fact_12': '一部のチョウは毎年数千キロメートルも移動します。',
      'bug_fact_13': 'カマキリは頭を180度回転できます。',
      'bug_fact_14': 'ノミは体長の200倍もジャンプできます。',
      'bug_fact_15': 'ナナフシは枝や葉に完璧に擬態します。',
      'bug_fact_16': 'ハチミツはミツバチの酵素のおかげで腐りません。',
      'bug_fact_17': 'アリの中には食用にキノコを育てるものもいます。',
      'bug_fact_18': 'セミは地下で最大17年間生きることができます。',
      'bug_fact_19': 'ヒアリは洪水時に生きたイカダを作って生き延びます。',
      'bug_fact_20': 'ボンバルディアビートルは熱い化学物質を噴射して身を守ります.',
    },
  };

  LanguageService() {
    _loadLanguage();
  }

  Future<void> _loadLanguage() async {
    final prefs = await SharedPreferences.getInstance();
    final languageCode = prefs.getString(_languageKey);
    if (languageCode != null) {
      _currentLocale = Locale(languageCode);
    }
    notifyListeners();
  }

  Future<void> setLanguage(String languageCode) async {
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(_languageKey, languageCode);
    _currentLocale = Locale(languageCode);
    notifyListeners();
  }

  Future<void> loadSavedLanguage() async {
    await _loadLanguage();
  }

  String getText(String key) {
    final languageCode = _currentLocale?.languageCode;
    if (languageCode != null && translations.containsKey(languageCode)) {
      final languageTranslations = translations[languageCode]!;
      return languageTranslations[key] ?? key;
    }
    // Fallback to English if no language is selected
    final englishTranslations = translations['en']!;
    return englishTranslations[key] ?? key;
  }

  Future<String> getCurrentLanguage() async {
    final prefs = await SharedPreferences.getInstance();
    return prefs.getString(_languageKey) ?? 'en';
  }

  Map<String, String> getSupportedLanguages() {
    return supportedLanguages.map((key, value) => MapEntry(key, value['name']!));
  }

  String getNativeName(String languageCode) {
    return supportedLanguages[languageCode]?['nativeName'] ?? languageCode;
  }

  String getFlag(String languageCode) {
    return supportedLanguages[languageCode]?['flag'] ?? '🏳️';
  }

  // Rastgele kaya gerçeği seç
  String getRandomBugFact() {
    final random = Random();
    final factNumber = random.nextInt(20) + 1;
    final factKey = 'bug_fact_' + factNumber.toString();
    return getText(factKey);
  }
} 
